import React from 'react';
import {
  LayoutDashboard,
  Home,
  Package,
  Boxes,
  Plus,
  Edit,
  Trash2,
  PlusCircle,
  Receipt,
  FileText,
  Printer,
  Share2,
  CreditCard,
  BarChart3,
  TrendingUp,
  PieChart,
  FileSpreadsheet,
  Calendar,
  Truck,
  ArrowDownLeft,
  ArrowUpRight,
  ShoppingBag,
  Users,
  UserCheck,
  Shield,
  Key,
  Store,
  Settings,
  Search,
  Filter,
  Download,
  RefreshCw,
  CheckCircle2,
  AlertCircle,
  AlertTriangle,
  Info,
  X,
  ChevronRight,
  ChevronDown,
  LogOut,
  Sun,
  Moon,
  Eye,
  EyeOff,
  ExternalLink,
  Clock,
  Phone,
  Mail,
  MapPin,
  Check,
  Award
} from 'lucide-react';

const iconMap = {
  dashboard: LayoutDashboard,
  home: Home,
  products: Package,
  boxes: Boxes,
  plus: Plus,
  edit: Edit,
  trash: Trash2,
  'trash-2': Trash2,
  'plus-circle': PlusCircle,
  invoice: Receipt,
  invoices: Receipt,
  receipt: Receipt,
  'file-text': FileText,
  print: Printer,
  printer: Printer,
  share: Share2,
  'credit-card': CreditCard,
  reports: BarChart3,
  'bar-chart': BarChart3,
  'trending-up': TrendingUp,
  'pie-chart': PieChart,
  csv: FileSpreadsheet,
  calendar: Calendar,
  purchases: Truck,
  truck: Truck,
  'stock-in': ArrowDownLeft,
  'arrow-down-left': ArrowDownLeft,
  'arrow-up-right': ArrowUpRight,
  'shopping-bag': ShoppingBag,
  users: Users,
  staff: Users,
  'user-check': UserCheck,
  shield: Shield,
  key: Key,
  store: Store,
  settings: Settings,
  search: Search,
  filter: Filter,
  download: Download,
  refresh: RefreshCw,
  'check-circle': CheckCircle2,
  'alert-circle': AlertCircle,
  'alert-triangle': AlertTriangle,
  info: Info,
  close: X,
  x: X,
  'chevron-right': ChevronRight,
  'chevron-down': ChevronDown,
  logout: LogOut,
  sun: Sun,
  moon: Moon,
  eye: Eye,
  'eye-off': EyeOff,
  'external-link': ExternalLink,
  clock: Clock,
  phone: Phone,
  mail: Mail,
  'map-pin': MapPin,
  check: Check,
  warranty: Award,
  award: Award
};

export const Icon = ({ name, size = 18, color, className = '', style = {}, ...props }) => {
  const IconComponent = iconMap[name?.toLowerCase()] || Info;
  return <IconComponent size={size} color={color} className={`lucide-icon ${className}`.trim()} style={style} {...props} />;
};

export default Icon;
