# Shop Configuration (Real Data — NOT committed to Git)
shop.name=MANISHA ELECTRONIC
shop.address=EDEN GROVE Building, Nr. State Bank of India, Opp. Govt. Higher Secondary, Thane Road, Valpoi, Satartia - Goa
shop.phone=9309736172, 70205592347
shop.gstin=30AMYPN1753F1ZY